#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Milan Nikolic <gen2brain@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

__author__ = "Milan Nikolic <gen2brain@gmail.com>"
__license__ = "GPL-3"
__version__ = "0.1.0"

import os
import sys
import signal
from optparse import OptionParser

if os.path.isdir(os.path.join(".","src")) and os.path.isfile(
        os.path.join(".","setup.py")):
    sys.path.append(os.path.realpath("src"))

try:
    from PyQt4.QtGui import QApplication
except ImportError, err:
    sys.stderr.write("Error: %s\n" % str(err))
    sys.exit(1)

try:
    from bgradio.main import BGRadio
    from bgradio import icons_rc
except ImportError, err:
    sys.stderr.write("Error: %s\n" % str(err))
    sys.exit(1)

def main():
    usage = "usage: %prog <options>"
    parser = OptionParser(usage=usage,
            version="BGRadio Version %s" % __version__)
    app = QApplication(sys.argv)
    QApplication.setApplicationName("BGRadio")
    opts, args = parser.parse_args()
    BGRadio(opts)

    try:
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        sys.exit(app.exec_())
    except KeyboardInterrupt:
        pass

if __name__ == "__main__":
    main()
